[package]
name = "reagent"
version = "0.1.0"
authors = ["Elf M. Sternberg <elf.sternberg@gmail.com>"]

[dependencies]
error-chain = "0.11.*"
mio = "0.6.10"

[dependencies.tokenpool]
path = "../tokenpool"

